version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - viagem_corporativa

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vue_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - viagem_corporativa

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: onfly
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: onfly
      MYSQL_PASSWORD: onfly_pass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - viagem_corporativa

networks:
  viagem_corporativa:
    driver: bridge

volumes:
  dbdata: